### ISSUE TITLE
Auto-pairs broke some files

### ISSUE THREAD

**Issue by heartb1t** [jiangmiao/auto-pairs#192]
I installed auto-pairs through vim-plug, and it all was fine (don't get me wrong, the plugin is amazing), but I just couldn't enjoy thing auto closing, I'd rather do them myself. But when I commented it on my .vimrc and tried to open another file in which auto-pairs had been loaded before I just couldn't do most of the things. Whenever I hit Backspace it would tell me: ```E117: Unknown function: AutoPairsDelete``` and ```E15: Invalid expression: AutoPairsDelete()```. That also happens to space, with ```AutoPairsSpace()```, any kind of auto closing pattern, with ```AutoPairsInsert('thing')``` and some other things that the plugin used to use. How can I get Vim to go back to normal?

**Comment by wangray** [comment]
@heartb1t I fixed this by clearing the `~/.vimviews` folder.

**Comment by filipelucas42** [comment]
I am having the same problem, using neovim version 0.4.3, I tried to uninstall the plugin to try some scripts unsuccessfully. I have already commented in vimrc, typed `PlugClean`, deleted manually in folder plugged. Whenever I type some quotes or try to delete something the following messages appear: E15: Invalid expression: AutoPairsDelete(), E15: Invalid expression: AutoPairsInsert(). I do not have any folder `~/.vimviews`. 

Edit Solved by deleting ~/.local/share/nvim/view

**Comment by timmyjose** [comment]
Unstarred this repo precisely because of that. I'm still stuck on `AutoPairsInsert`. Damn it.

**Comment by LunarWatcher** [comment]
What versions of Vim/Neovim are we talking about here? I can't repro in nvim 0.4.3 and 0.5.0 (preview), or in vim/gvim 8.0-8.2.2717. There's no obvious reason this should happen, even if there's some session fuckery going on.

I can't find any ways to trigger it through an explicit use of `mkview` and `loadview`, like the two other comments on here indicate, but that might be specific to [this vim distribution](https://github.com/spf13/spf13-vim) for all I know. (`.vimviews` is specific to that distribution; the default is `~/.vim/view` on UNIX distributions. and no defaults match `.vimviews`)

**Comment by timmyjose** [comment]
I'm using the following version of vim on macOS:

```
~/:$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 22 2021 19:39:30)
```

I managed to find all the view locations and clear them out. The errors have stopped appearing now.

**Comment by megahomyak** [comment]
I don't have a `view`/`.vimviews` file in every directory listed in this thread, but I'm still getting an error `Unknown function: AutoPairsDefine`. I am using NeoVIM and pathogen to use this plugin

**Comment by LunarWatcher** [comment]
@megahomyak in what context? What's your config?

**Comment by megahomyak** [comment]
Nevermind, I fixed it. It was my fault, not VIM, this plugin or something else. I promise that I'll never create some stupid comments like this

**Comment by z0xyz** [comment]
That equivalent of `~/.vimviews` and `~/.local/share/nvim/view` for vim is `~/.vim/views` by default.

**Comment by tup-olev** [comment]
Still a problem. `117: Unknown function: AutoPairsDelete`. The only fix is to delete files in the vim view directory.

**Comment by LunarWatcher** [comment]
There's no way to fix this on auto-pairs' end.

By default, vim sessions and views save `localoptions` and `options` respectively. These includes auto-pairs' buffer-local stuff, along with stuff for other plugins for that matter.

The only way to prevent this is removing these options from `sessionoptions`/`viewoptions`. However, this only applies _in advance._ If the error appears, it's too late to make this change (reinstalling auto-pairs to force a view regen might be an option, but I have not verified this). The view files have to be deleted, or manually edited to remove auto-pairs stuff when the error appears. 

Auto-pairs can't tell vim to selectively exclude auto-pairs options and leave everything else in place. The settings are on an everything or nothing basis. Shy of forcibly removing `localoptions` from `sessionoptions` and `options` from `viewoptions`, which certainly wouldn't be popular among the people who intentionally leave one or both in place, nothing can be done.

See also https://github.com/LunarWatcher/auto-pairs/issues/33#issuecomment-828535170

**Comment by tup-olev** [comment]
Would be prudent to at this to "Known Issues" on the main page.

**Comment by LunarWatcher** [comment]
That would require push access, which only jiangmiao has. See #309 for why that's a problem
